### ISSUE TITLE
Set up unit testing with the `testthat` package

### ISSUE THREAD

**Issue by dannyparsons** [IDEMSInternational/RInstatClimatic#3]
- [x] Follow the steps here https://r-pkgs.org/tests.html to set up the testing system.
- [x] Add some initial tests

**Comment by dannyparsons** [comment]
This may also be useful for testing ggplot outputs https://ggplot2.tidyverse.org/articles/ggplot2-in-packages.html#testing-ggplot2-output

**Comment by lilyclements** [comment]
Great. Will start on this now and perform some simple tests - like with `yday_366`, `dekad`, etc. I will need some discussion and examples before testing on a lot of the functions - e.g. the import/exports

**Comment by dannyparsons** [comment]
fixed by #23
